genetic_algorithm:
    num_generations: 10
    population_size: 10
    crossover_rate: 0.65
    mutation_rate: 0.05
    round_decimals: 6
    selection: "tournament" # tournament or roulette
    k: 10 # Number of individuals for the tournament selection
    repair: "cost_benefit" # random or cost_benefit
    num_parents_last_gen: 1

execution:
    num_runs: 10

log:
    output_path: "mknapcb1_results.txt"

data:
    metadata_path: "multidimensional_knapsack_instances/mknapcb1.txt"