genetic_algorithm:
    num_generations: 1000
    population_size: 1000
    crossover_rate: 0.65
    mutation_rate: 0.05
    round_decimals: 6
    plot_individuals: true
    selection: "tournament" # tournament or roulette
    k: 10 # Number of individuals for the tournament selection
    repair: "cost_benefit" # random or cost_benefit
    num_parents_last_gen: 1

execution:
    num_runs: 30

log:
    output_path: "mknapcb1_results.txt"

data:
    metadata_path: "/home/alefiury/Downloads/Instancias_Mochila_Multidimensional/Instancias Mochila Multidimensional/mknapcb1.txt"